name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./.docker/deploy/dockerfile --tag capo-optimizer-web-app-deploy
    - name: deploy
      run: docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY capo-optimizer-web-app-deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
